### ISSUE TITLE
Serie

### ISSUE THREAD

**Issue by MatiasFeldman** [pdepjm/2023-tp0-presentacion-EmiliaAndersen#2]
Por dios que buena serie, voy por la 4 temporada y me está encantando. ¿te viste alguna otra que te haya gustado? igual estoy como vos también hay que encontrar tiempo para ver series porque si no estoy durmiendo estoy o estudiando o en el gym.

**Comment by EmiliaAndersen** [comment]
Seguí viendola que cada vez se pone mejor.. Bueno, que recomiende: "Prison Break" y "Breaking Bad" o la precuela de GOT cuando la termines. Vos? Alguna otra que te haya gustado mucho?

**Comment by MatiasFeldman** [comment]
JAJJA increíble que las dos que vistes son series ya vi y que me encantaron, ahora estoy viendo agente nocturno en Netflix una nueva serie que me esta gustando bastante y Jack Ryan en prime video que posta esta espectacular.
